#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    i = 0
    points_a = 0
    points_b = 0
    while i < 3:
        if a[i] > b[i]:
            points_a += 1
        elif a[i] < b[i]:
            points_b += 1
        i += 1
    return(points_a, points_b)
            
            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
