#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    i = 0
    j = 0
    primary_total = 0
    secondary_total = 0
    diag_diff = 0
    while i < n:
        primary_total += arr[i][j]
        i += 1
        j += 1
    print(primary_total)
    i = n - 1
    j = 0
    while j < n:
        secondary_total += arr[i][j]
        j += 1
        i -= 1
    print(secondary_total)
    diag_diff = abs(primary_total - secondary_total)
    return(diag_diff)
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
