#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    i = 0
    pos = 0
    neg = 0
    zero = 0
    while i < n:
        if arr[i] > 0:
            pos += 1/n
        elif arr[i] < 0:
            neg += 1/n
        else:
            zero += 1/n
        i += 1
    print(pos)
    print(neg)
    print(zero)
        
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
