#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    i = 1
    spaces = n-1
    while spaces > -1:
        print(" "*(spaces) + "#"*i)
        i += 1
        spaces -= 1

if __name__ == '__main__':
    n = int(input())

    staircase(n)
