#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    time_1 = s[0:8]
    hour = int(time_1[0:2])
    if s[8:10] == "AM":
        if s[0:2] == "12":
            time_1 = "00" + time_1[2:8]
    elif s[8:10] == "PM":
        if s[0:2] != "12":
            time_1 = str(hour+12) + time_1[2:8] 
    return(time_1)
            
if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
