#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the arrayManipulation function below.
def arrayManipulation(n, queries):

    queryList = [ 0 for _ in range(n) ]
    
    for query in queries:
        
        lower, upper, num = list(map(int, query))
        
        lower -= 1
        upper -= 1
        
        for i in range(lower,upper+1):
            queryList[i] += num
        
        #print(queryList)
        
    max_val = max(queryList)
        
    return(max_val)
        
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
