#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dynamicArray' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def dynamicArray(n, queries):
    
    seqList = [ [] for _ in range(n) ]
    answer = []
    lastAnswer = 0
     
    for query in queries:
        
        query_type, a, b = list(map(int, query))    
        x = (a ^ lastAnswer) % n
        
        if query_type == 1:
            seqList[x].append(b)
            
        else:
            temp = seqList[x]
            lastAnswer = seqList[x][b % len(temp)]
            answer.append(lastAnswer)
            
    return(answer)
                    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    q = int(first_multiple_input[1])

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    result = dynamicArray(n, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
