#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c):
    
    i = 0
    jumps = 0
    c.append("X")
    c.append("X")

    while i < n-1:
        if c[i+2] == 0:
            i += 2
        elif c[i+1] == 0:
            i += 1
        jumps += 1
    
    return(jumps)
        
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
